version: "3.7"
services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./logs:/var/log/nginx
      - ./app:/var/www/app:rw
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    command: nginx -g "daemon off;"
    links:
      - php
  php:
    build: ./php
    volumes:
      - ./app:/var/www/app:rw
    command: php-fpm